spring.application.name=email-service

server.port=${SERVER_PORT:8084}
app.auth-server-url=${AUTH_SERVER_URL:http://localhost:8080}
spring.jpa.hibernate.ddl-auto=update

spring.rabbitmq.host=kebnekaise.lmq.cloudamqp.com
spring.rabbitmq.port=5671
spring.rabbitmq.username=zsrowtyu
spring.rabbitmq.password=mucDDAGJObCNshZosGsVf7309LK7Erc4
spring.rabbitmq.virtual-host=zsrowtyu
spring.rabbitmq.ssl.enabled=true

