name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Java with GitHub Packages auth
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          server-id: github
          server-username: GITHUB_ACTOR
          server-password: GITHUB_TOKEN
          cache: maven
        
      - name: Build with Maven
        run: mvn -B clean verify
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RABBITMQ_HOST: ${{ secrets.RABBITMQ_HOST }}
          RABBITMQ_PORT: ${{ secrets.RABBITMQ_PORT }}
          RABBITMQ_USERNAME: ${{ secrets.RABBITMQ_USERNAME }}
          RABBITMQ_PASSWORD: ${{ secrets.RABBITMQ_PASSWORD }}
          RABBITMQ_VHOST: ${{ secrets.RABBITMQ_VHOST }}
          MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
          MAIL_APP_PASSWORD: ${{ secrets.MAIL_APP_PASSWORD }}

