name: Java CI with Maven

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  packages: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Java with GitHub Packages auth
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          server-id: github
          server-username: GITHUB_ACTOR
          server-password: GITHUB_TOKEN
          cache: maven

      - name: Build project
        run: mvn -B clean package
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
